# config.yaml

## scraping PDFs
sitemap_url: "https://www.pedalpcb.com/sitemap-1.xml"
pdf_build_keyword: "build"
scraped_text_dir: "storage/scrapes"

## Input PDF file path
pdf_file_path: "storage/pdfs"

## API Keys
openai_api_key: "${OPENAI_API_KEY}"
langchain_api_key: "${LANGCHAIN_API_KEY}"
tavily_api_key: "${TAVILY_API_KEY}"
langsmith_api_key: "${LANGSMITH_API_KEY}"

## Tracing
langsmith_tracing_v2: "${LANGSMITH_TRACING_V2}"


